### ISSUE TITLE
Prototype the Front-end

### ISSUE THREAD

**Issue by davidhao3300** [ADI-Labs/calendar#11]
Meta issue for front-end:
- [x] #40 
- [x] #39 
- [x] #37
- [ ] Color code by event creator.
- [ ] Highlight current day somehow
- [x] Allow next week and previous week buttons #68

**Comment by alanhdu** [comment]
More issues:
- [ ] Color code by event creator.
- [ ] Highlight current day somehow
- [ ] Allow next week and previous week buttons #68
