### ISSUE TITLE
Remove hardcoded usernames/passwords from files

### ISSUE THREAD

**Issue by sunyang713** [ADI-Labs/calendar#134]
Not good to have these floating in a public repo. 

In general, I would advocate for handling of these kinds of 'keys' or 'constants' with a PyYaml and a `.secrets.yml` file instead of environment variables. For example:

``` yaml
username: REPLACE_WITH_USERNAME
password: REPLACE_WITH_PASSWORD
```

or something. Devs would manually edit the file locally, replacing the fields with the actual keys, but never commit the file with the secrets. The secrets should be communicated only verbally, no 'digital traces' (though it's a little late now). This would also remove the need to run `source settings.dev` every new session.

Otherwise anyone can access our databases right now and drop tables or the entire schema.

See:
- https://github.com/ADI-Labs/calendar/blob/master/config/bootstrap.sh#L10
- https://github.com/ADI-Labs/calendar/blob/master/config/settings.dev#L9

Here is a dumb-simple example from a class project:
- [.secrets.yml](https://github.com/sunyang713/liberated-server/blob/master/.config.yml)
- [Accessing and Using](https://github.com/sunyang713/liberated-server/blob/master/liberated/configure_engine.py)

**Comment by alanhdu** [comment]
This isn't actually a problem. 

In production, we'll be using a separate `config/settings.prod` file (not checked into the repo) to set the DB username + password as environment variables. All the passwords here are just for development.

**Comment by sunyang713** [comment]
ah okay, but what about the Facebook key? shouldn't that be hidden since it's actually connected to your FB app?

Also for why I want .config.yml over environment variables: https://support.cloud.engineyard.com/hc/en-us/articles/205407508-Environment-Variables-and-Why-You-Shouldn-t-Use-Them and typing `source config/settings.dev`

BUT, counter arg from heroku: 

> The traditional approach for handling such config vars is to put them under source - in a properties file of some sort. This is an error-prone process, and is especially complicated for open source apps which often have to maintain separate (and private) branches with app-specific configurations.
> 
> A better solution is to use environment variables, and keep the keys out of the code. On a traditional host or working locally you can set environment vars in your bashrc file. On Heroku, you use config vars.
