### ISSUE TITLE
more efficient event sorting

### ISSUE THREAD

**Issue by natebrennand** [ADI-Labs/calendar#46]
The home route uses a algorithm where a full iteration for each day of the week and should really only iterate a single time.

[code block](https://github.com/adicu/calendar/blob/218368f694ce62552bbb1d67856ba58cb340c16d/cal/__init__.py#L57-L63)

**Comment by alanhdu** [comment]
Removed from master, so no longer relevant.

In the future, `toolz.groupby` from [toolz](http://toolz.readthedocs.org/) would do the trick.
