### ISSUE TITLE
Web scraping: http://events.columbia.edu

### ISSUE THREAD

**Issue by alanhdu** [ADI-Labs/calendar#47]

**Comment by alanhdu** [comment]
@ohEmily. Are you planning to finish this, or should one of us pick it up?

**Comment by ohEmily** [comment]
I can work on it more! At the time I thought that someone else had taken
over, so I started to look at other issues.

**Comment by alanhdu** [comment]
Go for it. None of us are working on it right now.

We've been missing you in labs lately though... :confused:
